<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Forgot Your Password_input</name>
   <tag></tag>
   <elementGuidId>4a47c4cc-4af8-47bb-9977-90f84328daab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.input__container.session__form__input.session__form__password > input.input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49d66b83-58e7-4d66-bb92-910c2705112e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>24e1548b-6d0f-4f11-886b-4ab3ef8164bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^([1-9]\d{0,2}(,\d{3}){0,3})$|^([1-9]\d?(,\d{3}){4})$</value>
      <webElementGuid>36ac540c-d186-4e61-a7c2-d1adb6c6e58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>35630765-49c5-471d-bcba-2ff6f5337dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fffb941d-d194-43c2-b487-ec6f0fa60965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js dark&quot;]/body[1]/div[@class=&quot;app&quot;]/div[@class=&quot;desktop-layout&quot;]/div[@class=&quot;desktop-layout__content&quot;]/div[@class=&quot;desktop-layout__content__center&quot;]/div[@class=&quot;session__container&quot;]/div[@class=&quot;session&quot;]/div[@class=&quot;session__form&quot;]/div[@class=&quot;session__form__password__container&quot;]/div[@class=&quot;input__container session__form__input session__form__password&quot;]/input[@class=&quot;input&quot;]</value>
      <webElementGuid>d7999b29-d5e8-4bbe-a19d-6c94c40cf46a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>d58f0c90-cf90-46dc-909a-9d4eac53feda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>b4a77d8a-677a-4b4f-8b85-ab514f3d056a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password']</value>
      <webElementGuid>0eafe66b-70b7-4ba1-8587-490279298f9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
